name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.PAT }}
          deploy-branch: gh-pages
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_PROXY: ${{ secrets.AWS_PROXY }}
          AWS_SECRET: ${{ secrets.AWS_SECRET }}
          CAPTCHA_KEY: ${{ secrets.CAPTCHA_KEY }}
          CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
          MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
